// BinningUtility.hpp
// Utility functions for reading and using binning schemes
// Generated by AdaptiveBinning.cpp
//
// Author: EIC TDR Analysis Team
// Purpose: Helper functions to load binning schemes from file

#ifndef BINNING_UTILITY_HPP
#define BINNING_UTILITY_HPP

#include <vector>
#include <string>
#include <fstream>
#include <sstream>
#include <iostream>
#include <algorithm>

//==============================================================================
// STRUCTURE TO HOLD BINNING SCHEME
//==============================================================================
struct BinningScheme {
    std::vector<double> Q2_edges;
    std::vector<double> beta_edges;
    std::vector<double> xpom_edges;

    int nQ2() const { return Q2_edges.size() - 1; }
    int nBeta() const { return beta_edges.size() - 1; }
    int nXpom() const { return xpom_edges.size() - 1; }
    int nTotalBins() const { return nQ2() * nBeta() * nXpom(); }

    // Get bin indices for given values
    int GetQ2Bin(double Q2) const {
        for(int i = 0; i < nQ2(); i++) {
            if(Q2 >= Q2_edges[i] && Q2 < Q2_edges[i+1]) return i;
        }
        return -1; // Out of range
    }

    int GetBetaBin(double beta) const {
        for(int i = 0; i < nBeta(); i++) {
            if(beta >= beta_edges[i] && beta < beta_edges[i+1]) return i;
        }
        return -1; // Out of range
    }

    int GetXpomBin(double xpom) const {
        for(int i = 0; i < nXpom(); i++) {
            if(xpom >= xpom_edges[i] && xpom < xpom_edges[i+1]) return i;
        }
        return -1; // Out of range
    }

    // Get linear bin index from 3D indices
    // Hierarchy: Q2 (master) -> x_pom (secondary) -> beta (tertiary)
    int GetLinearBin(int iQ2, int iBeta, int iXpom) const {
        if(iQ2 < 0 || iQ2 >= nQ2()) return -1;
        if(iBeta < 0 || iBeta >= nBeta()) return -1;
        if(iXpom < 0 || iXpom >= nXpom()) return -1;
        return iQ2 * nBeta() * nXpom() + iXpom * nBeta() + iBeta;
    }

    // Get 3D indices from linear bin index
    void Get3DIndices(int linearBin, int& iQ2, int& iBeta, int& iXpom) const {
        iBeta = linearBin % nBeta();
        iXpom = (linearBin / nBeta()) % nXpom();
        iQ2 = linearBin / (nBeta() * nXpom());
    }
};

//==============================================================================
// FUNCTION TO READ BINNING SCHEME FROM FILE
//==============================================================================
inline BinningScheme ReadBinningScheme(const std::string& filename) {
    BinningScheme binning;

    std::ifstream infile(filename);
    if(!infile.is_open()) {
        std::cerr << "ERROR: Cannot open binning file " << filename << std::endl;
        return binning;
    }

    std::string line;
    while(std::getline(infile, line)) {
        // Skip empty lines and comments
        if(line.empty() || line[0] == '#') continue;

        std::istringstream iss(line);
        std::string keyword;
        iss >> keyword;

        if(keyword == "Q2_BINS") {
            int nEdges;
            iss >> nEdges;

            // Read next line with bin edges
            std::getline(infile, line);
            std::istringstream edgeStream(line);
            binning.Q2_edges.clear();
            double edge;
            while(edgeStream >> edge) {
                binning.Q2_edges.push_back(edge);
            }

            if((int)binning.Q2_edges.size() != nEdges) {
                std::cerr << "WARNING: Expected " << nEdges << " Q2 edges, found "
                          << binning.Q2_edges.size() << std::endl;
            }
        }
        else if(keyword == "BETA_BINS") {
            int nEdges;
            iss >> nEdges;

            // Read next line with bin edges
            std::getline(infile, line);
            std::istringstream edgeStream(line);
            binning.beta_edges.clear();
            double edge;
            while(edgeStream >> edge) {
                binning.beta_edges.push_back(edge);
            }

            if((int)binning.beta_edges.size() != nEdges) {
                std::cerr << "WARNING: Expected " << nEdges << " beta edges, found "
                          << binning.beta_edges.size() << std::endl;
            }
        }
        else if(keyword == "XPOM_BINS") {
            int nEdges;
            iss >> nEdges;

            // Read next line with bin edges
            std::getline(infile, line);
            std::istringstream edgeStream(line);
            binning.xpom_edges.clear();
            double edge;
            while(edgeStream >> edge) {
                binning.xpom_edges.push_back(edge);
            }

            if((int)binning.xpom_edges.size() != nEdges) {
                std::cerr << "WARNING: Expected " << nEdges << " xpom edges, found "
                          << binning.xpom_edges.size() << std::endl;
            }
        }
    }

    infile.close();

    // Verify that we read all three sets of bin edges
    if(binning.Q2_edges.empty()) {
        std::cerr << "ERROR: No Q2 bin edges found in " << filename << std::endl;
    }
    if(binning.beta_edges.empty()) {
        std::cerr << "ERROR: No beta bin edges found in " << filename << std::endl;
    }
    if(binning.xpom_edges.empty()) {
        std::cerr << "ERROR: No xpom bin edges found in " << filename << std::endl;
    }

    return binning;
}

//==============================================================================
// FUNCTION TO PRINT BINNING SCHEME SUMMARY
//==============================================================================
inline void PrintBinningScheme(const BinningScheme& binning) {
    std::cout << "\n=== Binning Scheme ===" << std::endl;
    std::cout << "Q² bins: " << binning.nQ2() << std::endl;
    std::cout << "  Range: [" << binning.Q2_edges.front() << ", "
              << binning.Q2_edges.back() << "]" << std::endl;

    std::cout << "Beta bins: " << binning.nBeta() << std::endl;
    std::cout << "  Range: [" << binning.beta_edges.front() << ", "
              << binning.beta_edges.back() << "]" << std::endl;

    std::cout << "x_pom bins: " << binning.nXpom() << std::endl;
    std::cout << "  Range: [" << binning.xpom_edges.front() << ", "
              << binning.xpom_edges.back() << "]" << std::endl;

    std::cout << "Total bins: " << binning.nTotalBins() << " = "
              << binning.nQ2() << " × " << binning.nBeta() << " × "
              << binning.nXpom() << std::endl;
}

//==============================================================================
// EXAMPLE USAGE IN ANALYSIS CODE
//==============================================================================
/*

// In your analysis code:

#include "BinningUtility.hpp"

// Load binning scheme from file
BinningScheme binning = ReadBinningScheme("binning_scheme.txt");
PrintBinningScheme(binning);

// Create histogram with custom binning
TH3D* h = new TH3D("h_d3sigma", "Triple Differential Cross Section;Q^{2};#beta;x_{pom}",
                   binning.nQ2(), binning.Q2_edges.data(),
                   binning.nBeta(), binning.beta_edges.data(),
                   binning.nXpom(), binning.xpom_edges.data());

// Fill histogram for each event
for(auto& event : events) {
    h->Fill(event.Q2, event.beta, event.xpom, event.weight);
}

// Or get bin indices manually
int iQ2 = binning.GetQ2Bin(myQ2);
int iBeta = binning.GetBetaBin(myBeta);
int iXpom = binning.GetXpomBin(myXpom);

if(iQ2 >= 0 && iBeta >= 0 && iXpom >= 0) {
    int linearBin = binning.GetLinearBin(iQ2, iBeta, iXpom);
    // Do something with the bin index
}

*/

#endif // BINNING_UTILITY_HPP
