// Example: How to use the binning scheme generated by AdaptiveBinning
// This demonstrates loading and using custom bin edges in your analysis
//
// Compile: g++ Example_UseBinning.cpp -o Example_UseBinning $(root-config --cflags --glibs)
// Run: ./Example_UseBinning binning_scheme.txt
//
// Author: EIC TDR Analysis Team
// Purpose: Example code showing integration of adaptive binning

#include <TROOT.h>
#include <TFile.h>
#include <TH1D.h>
#include <TH2D.h>
#include <TH3D.h>
#include <TCanvas.h>
#include <TStyle.h>
#include <TRandom.h>
#include <TMath.h>

#include <iostream>
#include <vector>
#include <string>

// Include the binning utility header
#include "BinningUtility.hpp"

//==============================================================================
// EXAMPLE 1: Create histogram with custom binning
//==============================================================================
void Example1_CreateHistogram(const BinningScheme& binning) {
    std::cout << "\n=== Example 1: Creating Histogram with Custom Binning ===" << std::endl;

    // Create 3D histogram with the custom binning
    TH3D* h_d3sigma = new TH3D("h_d3sigma",
                               "Triple Differential Cross Section;Q^{2} [GeV^{2}];#beta;x_{pom}",
                               binning.nQ2(), binning.Q2_edges.data(),
                               binning.nBeta(), binning.beta_edges.data(),
                               binning.nXpom(), binning.xpom_edges.data());

    std::cout << "Created TH3D with custom binning:" << std::endl;
    std::cout << "  X-axis (Q²): " << h_d3sigma->GetNbinsX() << " bins" << std::endl;
    std::cout << "  Y-axis (beta): " << h_d3sigma->GetNbinsY() << " bins" << std::endl;
    std::cout << "  Z-axis (x_pom): " << h_d3sigma->GetNbinsZ() << " bins" << std::endl;
    std::cout << "  Total bins: " << (h_d3sigma->GetNbinsX() * h_d3sigma->GetNbinsY() * h_d3sigma->GetNbinsZ()) << std::endl;

    // Example: Fill with some dummy data
    std::cout << "\nFilling histogram with dummy data..." << std::endl;
    for(int i = 0; i < 10000; i++) {
        // Generate random values within ranges
        double Q2 = binning.Q2_edges.front() +
                    (binning.Q2_edges.back() - binning.Q2_edges.front()) * gRandom->Rndm();
        double beta = binning.beta_edges.front() +
                      (binning.beta_edges.back() - binning.beta_edges.front()) * gRandom->Rndm();
        double xpom = binning.xpom_edges.front() +
                      (binning.xpom_edges.back() - binning.xpom_edges.front()) * gRandom->Rndm();

        h_d3sigma->Fill(Q2, beta, xpom);
    }

    std::cout << "Histogram entries: " << h_d3sigma->GetEntries() << std::endl;

    // Save to file
    TFile* outfile = new TFile("example_histogram.root", "RECREATE");
    h_d3sigma->Write();
    outfile->Close();
    std::cout << "Saved histogram to: example_histogram.root" << std::endl;

    delete h_d3sigma;
}

//==============================================================================
// EXAMPLE 2: Get bin indices for specific values
//==============================================================================
void Example2_GetBinIndices(const BinningScheme& binning) {
    std::cout << "\n=== Example 2: Getting Bin Indices for Values ===" << std::endl;

    // Example values
    double Q2_value = 10.0;
    double beta_value = 0.35;
    double xpom_value = 0.015;

    std::cout << "For values: Q² = " << Q2_value
              << ", beta = " << beta_value
              << ", x_pom = " << xpom_value << std::endl;

    // Get bin indices
    int iQ2 = binning.GetQ2Bin(Q2_value);
    int iBeta = binning.GetBetaBin(beta_value);
    int iXpom = binning.GetXpomBin(xpom_value);

    if(iQ2 >= 0 && iBeta >= 0 && iXpom >= 0) {
        std::cout << "Bin indices: Q²[" << iQ2 << "], beta[" << iBeta << "], x_pom[" << iXpom << "]" << std::endl;

        // Get bin ranges
        std::cout << "Bin ranges:" << std::endl;
        std::cout << "  Q²: [" << binning.Q2_edges[iQ2] << ", " << binning.Q2_edges[iQ2+1] << "]" << std::endl;
        std::cout << "  beta: [" << binning.beta_edges[iBeta] << ", " << binning.beta_edges[iBeta+1] << "]" << std::endl;
        std::cout << "  x_pom: [" << binning.xpom_edges[iXpom] << ", " << binning.xpom_edges[iXpom+1] << "]" << std::endl;

        // Get linear bin index
        int linearBin = binning.GetLinearBin(iQ2, iBeta, iXpom);
        std::cout << "Linear bin index: " << linearBin << std::endl;

        // Convert back to 3D indices
        int iQ2_back, iBeta_back, iXpom_back;
        binning.Get3DIndices(linearBin, iQ2_back, iBeta_back, iXpom_back);
        std::cout << "Converted back: Q²[" << iQ2_back << "], beta[" << iBeta_back << "], x_pom[" << iXpom_back << "]" << std::endl;
    } else {
        std::cout << "ERROR: One or more values are out of range!" << std::endl;
        if(iQ2 < 0) std::cout << "  Q² value " << Q2_value << " is outside range" << std::endl;
        if(iBeta < 0) std::cout << "  beta value " << beta_value << " is outside range" << std::endl;
        if(iXpom < 0) std::cout << "  x_pom value " << xpom_value << " is outside range" << std::endl;
    }
}

//==============================================================================
// EXAMPLE 3: Create 1D projections for each bin
//==============================================================================
void Example3_Create1DProjections(const BinningScheme& binning) {
    std::cout << "\n=== Example 3: Creating 1D Projections ===" << std::endl;

    // Example: Create 1D histograms for each (Q², beta) bin showing x_pom distribution
    TFile* outfile = new TFile("example_projections.root", "RECREATE");

    int nProjections = 0;
    for(int iQ2 = 0; iQ2 < binning.nQ2(); iQ2++) {
        for(int iBeta = 0; iBeta < binning.nBeta(); iBeta++) {
            // Create histogram name
            TString hname = Form("h_xpom_Q2_%d_beta_%d", iQ2, iBeta);
            TString htitle = Form("x_{pom} for Q^{2}=[%.1f,%.1f], #beta=[%.2f,%.2f]",
                                 binning.Q2_edges[iQ2], binning.Q2_edges[iQ2+1],
                                 binning.beta_edges[iBeta], binning.beta_edges[iBeta+1]);

            // Create 1D histogram with custom x_pom binning
            TH1D* h = new TH1D(hname, htitle + ";x_{pom};d^{3}#sigma",
                              binning.nXpom(), binning.xpom_edges.data());

            h->Write();
            delete h;
            nProjections++;
        }
    }

    outfile->Close();
    std::cout << "Created " << nProjections << " 1D projection histograms" << std::endl;
    std::cout << "Saved to: example_projections.root" << std::endl;
}

//==============================================================================
// EXAMPLE 4: Print all bin edges in a formatted way
//==============================================================================
void Example4_PrintAllBinEdges(const BinningScheme& binning) {
    std::cout << "\n=== Example 4: Printing All Bin Edges ===" << std::endl;

    std::cout << "\nQ² bin edges:" << std::endl;
    for(int i = 0; i < binning.nQ2(); i++) {
        std::cout << "  Bin " << i << ": [" << binning.Q2_edges[i]
                  << ", " << binning.Q2_edges[i+1] << "] GeV²"
                  << "  (width = " << (binning.Q2_edges[i+1] - binning.Q2_edges[i]) << ")" << std::endl;
    }

    std::cout << "\nBeta bin edges:" << std::endl;
    for(int i = 0; i < binning.nBeta(); i++) {
        std::cout << "  Bin " << i << ": [" << binning.beta_edges[i]
                  << ", " << binning.beta_edges[i+1] << "]"
                  << "  (width = " << (binning.beta_edges[i+1] - binning.beta_edges[i]) << ")" << std::endl;
    }

    std::cout << "\nx_pom bin edges:" << std::endl;
    for(int i = 0; i < binning.nXpom(); i++) {
        std::cout << "  Bin " << i << ": [" << binning.xpom_edges[i]
                  << ", " << binning.xpom_edges[i+1] << "]"
                  << "  (width = " << (binning.xpom_edges[i+1] - binning.xpom_edges[i]) << ")" << std::endl;
    }
}

//==============================================================================
// EXAMPLE 5: Create 2D projections
//==============================================================================
void Example5_Create2DProjections(const BinningScheme& binning) {
    std::cout << "\n=== Example 5: Creating 2D Projections ===" << std::endl;

    // Create 2D histograms showing different projections
    TH2D* h_Q2_vs_xpom = new TH2D("h_Q2_vs_xpom",
                                   "Binning Scheme: Q^{2} vs x_{pom};log_{10}(x_{pom});Q^{2} [GeV^{2}]",
                                   100, TMath::Log10(binning.xpom_edges.front()),
                                   TMath::Log10(binning.xpom_edges.back()),
                                   100, binning.Q2_edges.front(), binning.Q2_edges.back());

    TH2D* h_Q2_vs_beta = new TH2D("h_Q2_vs_beta",
                                   "Binning Scheme: Q^{2} vs #beta;#beta;Q^{2} [GeV^{2}]",
                                   100, binning.beta_edges.front(), binning.beta_edges.back(),
                                   100, binning.Q2_edges.front(), binning.Q2_edges.back());

    TH2D* h_beta_vs_xpom = new TH2D("h_beta_vs_xpom",
                                     "Binning Scheme: #beta vs x_{pom};log_{10}(x_{pom});#beta",
                                     100, TMath::Log10(binning.xpom_edges.front()),
                                     TMath::Log10(binning.xpom_edges.back()),
                                     100, binning.beta_edges.front(), binning.beta_edges.back());

    // Draw bin boundaries as lines
    // This is just a demonstration - in real use you'd draw lines on the histograms

    TFile* outfile = new TFile("example_2d_projections.root", "RECREATE");
    h_Q2_vs_xpom->Write();
    h_Q2_vs_beta->Write();
    h_beta_vs_xpom->Write();
    outfile->Close();

    std::cout << "Created 2D projection histograms" << std::endl;
    std::cout << "Saved to: example_2d_projections.root" << std::endl;

    delete h_Q2_vs_xpom;
    delete h_Q2_vs_beta;
    delete h_beta_vs_xpom;
}

//==============================================================================
// MAIN PROGRAM
//==============================================================================
int main(int argc, char** argv) {
    std::cout << "\n================================================" << std::endl;
    std::cout << "  EXAMPLE: Using Adaptive Binning in Analysis" << std::endl;
    std::cout << "================================================\n" << std::endl;

    // Get binning file from command line or prompt user
    std::string binningFile;
    if(argc > 1) {
        binningFile = argv[1];
    } else {
        std::cout << "Enter binning scheme filename: ";
        std::cin >> binningFile;
    }

    // Load binning scheme from file
    std::cout << "Loading binning scheme from: " << binningFile << std::endl;
    BinningScheme binning = ReadBinningScheme(binningFile);

    // Check if binning was loaded successfully
    if(binning.Q2_edges.empty() || binning.beta_edges.empty() || binning.xpom_edges.empty()) {
        std::cout << "ERROR: Failed to load binning scheme!" << std::endl;
        return 1;
    }

    // Print summary
    PrintBinningScheme(binning);

    // Run examples
    Example1_CreateHistogram(binning);
    Example2_GetBinIndices(binning);
    Example3_Create1DProjections(binning);
    Example4_PrintAllBinEdges(binning);
    Example5_Create2DProjections(binning);

    std::cout << "\n================================================" << std::endl;
    std::cout << "  EXAMPLES COMPLETE!" << std::endl;
    std::cout << "================================================\n" << std::endl;
    std::cout << "Created files:" << std::endl;
    std::cout << "  - example_histogram.root" << std::endl;
    std::cout << "  - example_projections.root" << std::endl;
    std::cout << "  - example_2d_projections.root" << std::endl;
    std::cout << "\nYou can now use these patterns in your own analysis code!" << std::endl;

    return 0;
}
